version: '3'

services:
  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "3001:3001"
    env_file:
      - ./dashboard/.env
